### ISSUE TITLE
doubt 

### ISSUE THREAD

**Issue by hariari** [lbraglia/chtp#6]
prog:5.19.c(dietel c How to progarm)

problem:can you please help me find the bug in the following program written by me?please spend 2 minutes for me.I am trying to find the bug since an hour but could not find out.please help me.

#include<stdio.h>
void anyCharacter(int side,char fillCharacter);
int main(void)
{
	int side=90;
	char fillCharacter='*';
	anyCharacter(side,fillCharacter);
}//end main
void anyCharacter(int side,char fillCharacter)
{
	int dummySide=side;
	for(side=1;side<=dummySide;side++)
	{
		for(side=1;side<=dummySide;side++)
		{
			printf("%c",fillCharacter);
		}//end inner for
		printf("\n");
	}//end outer for
}//end function fill character

**Comment by bengunur06** [comment]
Hey the  bug is in the for loops in the function first for is  true but
then in the second loop entering you equaled side again to 1 and end of the
loop side will be equal to condition when it's out of loop the first for
loop condition will also be false then both for loops will be finished my
advicadvice to you is that after the first loop use a garbage value to
execute second loop put something else in side in the second for loop then
Bug But will be fixed I think

3 Oca 2018 21:22 tarihinde "hariari" <notifications@github.com> yazdı:

**Comment by bengunur06** [comment]
And what the program should do if you want to print square asteriks also
you should put printf with \n after the second loop so when it finishes the
second loop it will print  asteriks to  another line

3 Oca 2018 21:53 tarihinde "bensu baş" <bengunur2@gmail.com> yazdı:

**Comment by elhaw** [comment]
You need to add **two** things in your existing code.

 1.Define another variable `int column;` after `int dummySide=side;
` inside your function definition.

2.Replace the side variable in the second for loop which is `side` with the new variable `column`

**The code after modification**  
`#include<stdio.h>

  void anyCharacter(int side,char fillCharacter);
  int main(void)
  {
    int side=3;
    char fillCharacter='*';
    anyCharacter(side,fillCharacter);
  }//end main


  void anyCharacter(int side,char fillCharacter)
  {
    int dummySide=side;
    //define new variable for the inner loop
    int coloumn;
    for(side=1;side<=dummySide;side++)
    {
      for(coloumn =1;coloumn<=dummySide;coloumn++)
      {
        printf("%c",fillCharacter);
      }//end inner for
    printf("\n");
    }//end outer for
  }//end function fill character
`
